name: Run C++ Application

on:
    workflow_dispatch

jobs:
    run:
        runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DPATCH_VERSION=${{ github.run_number }} \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build application
        run: cmake --build build --target hello-world

      - name: Run application
        run: ./build/hello-world